name: Publish
on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  AZURE_WEBAPP_NAME: mytimeservice
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'	

      - name: Restore
        run: dotnet restore ./TestCoreApp.fsproj

      - name: Build
        run: dotnet build ./TestCoreApp.fsproj --configuration Release --no-restore


      - name: Publish
        run: dotnet publish ./TestCoreApp.fsproj --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

      - name: Deployement
        uses: actions/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}


    

      
    
  
    
     
    
